server:
  port: 9527

spring:
  application:
    name: ddc-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 119.29.159.39:8848
    gateway:
      routes: #配置路由路径
        # user模块
        - id: user-route # 路由名（不重复就行）
          uri: lb://ddc-user # lb://模块
          predicates:
            #- Path=/oauth/token, /rsa/publicKey # 多个可匹配的用,分割
            - Path=/user/** # 匹配/user开头的请求
          filters:
            - StripPrefix=1 # 去除请求路径中的"/user"前缀(即网关请求其他模块时去掉前缀，不需要就不写)
        # 添加其他模块
#        - id: users-route
#          uri: lb://micro-users
#          predicates:
#            - Path=/users/** # 匹配以”/users“开头的路径
#          filters:
#            - StripPrefix=1 # 去除请求路径中的"/users"前缀
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写

